POST http://localhost:8080/api/account
Content-Type: application/json

{
  "name": "adam"
}

###

POST http://localhost:8080/api/address
Content-Type: application/json

{
  "accountId": 1
}

###

GET http://localhost:8080/api/address?id=2
###

POST http://localhost:8080/api/team
Content-Type: application/json

{
  "name": "adam's team 3",
  "ownerId": 1
}

###

GET  http://localhost:8080/api/team?id=2


###
GET  http://localhost:8080/api/account?id=1

###
GET  http://localhost:8080/api/address?id=2


